'use client';

import { useState } from 'react';
import Link from 'next/link';
import { Sparkles, ArrowRight } from 'lucide-react';
import { Badge, Button, Card, Textarea } from '@/components/ui';

/**
 * The live, unauthenticated demo.
 *
 * Only rendered when the server has confirmed a provider is configured and
 * rate limiting is distributed, so there is no "unavailable" state to design
 * for here — if it renders, it can run.
 *
 * Three things it is careful about:
 *
 *  - **The rate limit is surfaced as a wait, not a failure.** 429 is the
 *    expected outcome of a tight limit working, and "Too many requests" with
 *    no number leaves a visitor clicking again immediately, which is exactly
 *    what the limit is trying to prevent.
 *  - **The result says which provider produced it**, rather than implying a
 *    house model.
 *  - **It is labelled a sketch**, because it is three fields from a 300-token
 *    call. Presenting it as what the product produces would oversell the demo
 *    and then disappoint on signup.
 */

interface Sketch {
  tagline: string;
  voice: string[];
  audience: string;
}

const EXAMPLE = 'A small-batch ceramics studio in Lisbon selling hand-thrown tableware to restaurants.';

export function DemoForm() {
  const [description, setDescription] = useState('');
  const [sketch, setSketch] = useState<Sketch | null>(null);
  const [provider, setProvider] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  async function generate(event: React.FormEvent) {
    event.preventDefault();
    if (loading) return;

    setLoading(true);
    setError(null);
    setSketch(null);

    try {
      const response = await fetch('/api/public/demo', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ description }),
      });
      const body = await response.json();

      if (response.status === 429) {
        // Turn the limit into an instruction. Without the number, the natural
        // response is to click again, which is what the limit exists to stop.
        const wait = body?.details?.retryAfterSeconds;
        throw new Error(
          wait
            ? `The free demo is limited to keep it free. Try again in ${wait} second${wait === 1 ? '' : 's'}.`
            : 'The free demo is rate limited. Please try again shortly.'
        );
      }

      if (!response.ok) throw new Error(body?.error ?? 'Could not generate a sketch.');

      setSketch(body.sketch);
      setProvider(body.provider ?? null);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Could not generate a sketch.');
    } finally {
      setLoading(false);
    }
  }

  return (
    <Card className="p-6">
      <form onSubmit={generate} noValidate>
        <Textarea
          label="Describe the business"
          hint="One or two lines is enough. 20 characters minimum."
          value={description}
          onChange={(event) => setDescription(event.target.value)}
          minLength={20}
          maxLength={400}
          rows={3}
          placeholder={EXAMPLE}
          required
        />

        <div className="mt-4 flex flex-wrap items-center gap-3">
          <Button type="submit" loading={loading} icon={<Sparkles className="h-4 w-4" />}>
            {loading ? 'Sketching…' : 'Sketch the brand'}
          </Button>

          <button
            type="button"
            onClick={() => setDescription(EXAMPLE)}
            className="text-xs font-medium text-primary underline underline-offset-2"
          >
            Use the example
          </button>

          <span className="ml-auto text-xs text-content-tertiary">No account needed</span>
        </div>
      </form>

      {error && (
        <p
          role="alert"
          className="mt-4 rounded-md bg-danger-subtle px-3 py-2 text-sm font-medium text-danger"
        >
          {error}
        </p>
      )}

      {sketch && (
        <div className="mt-6 border-t border-[color:var(--color-border)] pt-6 animate-fade-in">
          <div className="flex flex-wrap items-center gap-2">
            <Badge tone="ai">Sketch</Badge>
            {provider && <span className="text-xs text-content-tertiary">generated by {provider}</span>}
          </div>

          <p className="mt-4 text-xl font-semibold leading-snug text-content">{sketch.tagline}</p>

          <dl className="mt-5 grid gap-4 sm:grid-cols-2">
            <div>
              <dt className="text-xs font-medium uppercase tracking-wide text-content-tertiary">Voice</dt>
              <dd className="mt-1.5 flex flex-wrap gap-1.5">
                {sketch.voice.map((trait) => (
                  <span key={trait} className="badge-neutral">
                    {trait}
                  </span>
                ))}
              </dd>
            </div>
            <div>
              <dt className="text-xs font-medium uppercase tracking-wide text-content-tertiary">Audience</dt>
              <dd className="mt-1.5 text-sm leading-6 text-content-secondary">{sketch.audience}</dd>
            </div>
          </dl>

          <div className="mt-6 flex flex-wrap items-center gap-3 rounded-md bg-surface-raised p-4">
            <p className="min-w-0 flex-1 text-sm leading-6 text-content-secondary">
              This is three fields. A real Brand Brain also stores positioning, the claims you are allowed to
              make, and the ones you are not — and every generation afterwards reads it.
            </p>
            <Link href="/signup">
              <Button size="sm" icon={<ArrowRight className="h-3.5 w-3.5" />}>
                Build the full brand
              </Button>
            </Link>
          </div>
        </div>
      )}
    </Card>
  );
}
