'use client';
import { useEffect, useState } from 'react';
import { Camera, Loader2, Package, Plus, Sparkles, Upload, X } from 'lucide-react';
import { toast } from 'sonner';
import { supabaseBrowser } from '@/lib/supabase/client';

type Product={id:string;name:string;description:string;category:string;price:number|null;currency:string;stock:number};
type Asset={id:string;product_id:string;url:string;type:string;status:string;analysis:any;metadata:any;signedUrl?:string};

export default function Products(){
 const [brands,setBrands]=useState<any[]>([]),[brandId,setBrandId]=useState(''),[products,setProducts]=useState<Product[]>([]),[selected,setSelected]=useState<Product|null>(null);
 const [assets,setAssets]=useState<Asset[]>([]),[name,setName]=useState(''),[category,setCategory]=useState(''),[price,setPrice]=useState(''),[desc,setDesc]=useState(''),[loading,setLoading]=useState(false),[uploading,setUploading]=useState(false),[analyzing,setAnalyzing]=useState<string|null>(null);
 useEffect(()=>{fetch('/api/brands').then(r=>r.json()).then(d=>{setBrands(d.brands||[]);if(d.brands?.[0])setBrandId(d.brands[0].id)})},[]);
 useEffect(()=>{if(!brandId)return;fetch(`/api/products?brandId=${brandId}`).then(r=>r.json()).then(d=>setProducts(d.products||[]));setSelected(null);setAssets([])},[brandId]);
 async function add(){if(!brandId||!name.trim())return;setLoading(true);try{const r=await fetch('/api/products',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({brandId,name,category,description:desc,price:price?Number(price):null})});const d=await r.json();if(!r.ok)throw new Error(d.error);setProducts(p=>[d.product,...p]);setSelected(d.product);setName('');setCategory('');setPrice('');setDesc('');toast.success('Product added.')}catch(e){toast.error(e instanceof Error?e.message:'Could not add product.')}finally{setLoading(false)}}
 async function openProduct(p:Product){setSelected(p);const r=await fetch(`/api/products?brandId=${brandId}&productId=${p.id}`);const d=await r.json();setAssets(d.assets||[]);}
 async function upload(files:FileList|null){if(!files||!selected||!brandId)return;setUploading(true);try{const sb=supabaseBrowser();for(const file of Array.from(files)){if(!file.type.startsWith('image/'))continue;const r=await fetch('/api/media/upload',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({brandId,productId:selected.id,fileName:file.name,contentType:file.type})});const d=await r.json();if(!r.ok)throw new Error(d.error);const up=await sb.storage.from('owbrand-media').uploadToSignedUrl(d.path,d.token,file);if(up.error)throw up.error;const url=await fetch('/api/media/url',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:d.path})}).then(x=>x.json());setAssets(a=>[{...d.asset,signedUrl:url.url},...a]);}toast.success('Product photos uploaded.');}catch(e){toast.error(e instanceof Error?e.message:'Upload failed.')}finally{setUploading(false)}}
 async function analyze(asset:Asset){setAnalyzing(asset.id);try{const r=await fetch('/api/media/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({assetId:asset.id,brandId})});const d=await r.json();if(!r.ok)throw new Error(d.error);setAssets(a=>a.map(x=>x.id===asset.id?{...x,...d.asset,analysis:d.analysis}:x));toast.success('Product image analyzed.')}catch(e){toast.error(e instanceof Error?e.message:'Analysis failed.')}finally{setAnalyzing(null)}}
 return <div className="mx-auto max-w-7xl space-y-7">
  <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="section-eyebrow">Product intelligence</p><h1 className="mt-3 font-display text-3xl font-bold">Products</h1><p className="mt-1 text-sm text-ink-soft">Upload ordinary product photos. OwBrand analyzes them and prepares them for professional creative production.</p></div>{brands.length>0&&<select value={brandId} onChange={e=>setBrandId(e.target.value)} className="rounded-xl border border-line bg-white px-4 py-2.5 text-sm">{brands.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select>}</div>
  <div className="grid gap-5 lg:grid-cols-[330px_1fr]">
   <section className="glass-panel p-6"><h2 className="font-display text-lg font-semibold">Add product</h2><div className="mt-5 space-y-3"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Product name" className="w-full rounded-xl border border-line bg-white px-4 py-2.5 text-sm"/><input value={category} onChange={e=>setCategory(e.target.value)} placeholder="Category" className="w-full rounded-xl border border-line bg-white px-4 py-2.5 text-sm"/><input value={price} onChange={e=>setPrice(e.target.value)} placeholder="Price" inputMode="decimal" className="w-full rounded-xl border border-line bg-white px-4 py-2.5 text-sm"/><textarea value={desc} onChange={e=>setDesc(e.target.value)} rows={5} placeholder="Features, benefits, ingredients, materials, use cases..." className="w-full rounded-xl border border-line bg-white px-4 py-3 text-sm"/><button onClick={add} disabled={loading} className="btn-accent w-full">{loading?<Loader2 className="h-4 w-4 animate-spin"/>:<Plus className="h-4 w-4"/>}{loading?'Adding...':'Add product'}</button></div></section>
   <section className="grid gap-3 sm:grid-cols-2">{products.map(p=><button onClick={()=>openProduct(p)} key={p.id} className={`rounded-2xl border bg-white p-5 text-left transition hover:-translate-y-0.5 ${selected?.id===p.id?'border-ink shadow-sm':'border-line'}`}><div className="flex items-start justify-between"><div className="rounded-xl bg-canvas-alt p-2"><Package className="h-5 w-5"/></div><span className="text-xs text-ink-faint">{p.category||'Product'}</span></div><h3 className="mt-4 font-display text-lg font-semibold">{p.name}</h3><p className="mt-2 line-clamp-3 text-sm text-ink-soft">{p.description||'No description yet.'}</p><div className="mt-4 flex justify-between text-xs"><span>{p.price!=null?`${p.currency||'USD'} ${p.price}`:'Price not set'}</span><span>{p.stock||0} in stock</span></div></button>)}{products.length===0&&<div className="sm:col-span-2 rounded-2xl border border-dashed border-line bg-white p-12 text-center text-sm text-ink-soft">No products yet. Add your first product.</div>}</section>
  </div>
  {selected&&<section className="glass-panel p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="section-eyebrow">Product Photo Studio</p><h2 className="mt-2 font-display text-2xl font-bold">{selected.name}</h2><p className="mt-1 text-sm text-ink-soft">Start with real product photos. AI analysis locks onto the product before creative generation.</p></div><label className="btn-accent cursor-pointer"><Upload className="h-4 w-4"/>{uploading?'Uploading...':'Upload photos'}<input type="file" accept="image/jpeg,image/png,image/webp" multiple className="hidden" disabled={uploading} onChange={e=>upload(e.target.files)}/></label></div>
   <div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{assets.map(a=><article key={a.id} className="overflow-hidden rounded-2xl border border-line bg-white"><div className="aspect-[4/3] bg-canvas-alt">{a.signedUrl?<img src={a.signedUrl} alt={selected.name} className="h-full w-full object-contain"/>:<div className="flex h-full items-center justify-center text-sm text-ink-faint"><Camera className="mr-2 h-5 w-5"/>Original uploaded</div>}</div><div className="p-4"><div className="flex items-center justify-between"><span className="rounded-full bg-canvas-alt px-2.5 py-1 text-[11px] font-semibold">{a.status}</span><button onClick={()=>analyze(a)} disabled={analyzing===a.id} className="inline-flex items-center gap-1.5 text-xs font-semibold text-ink">{analyzing===a.id?<Loader2 className="h-3.5 w-3.5 animate-spin"/>:<Sparkles className="h-3.5 w-3.5"/>}Analyze</button></div>{a.analysis&&<pre className="mt-3 max-h-40 overflow-auto whitespace-pre-wrap text-[11px] leading-5 text-ink-soft">{typeof a.analysis==='string'?a.analysis:JSON.stringify(a.analysis,null,2)}</pre>}</div></article>)}{assets.length===0&&<div className="md:col-span-2 xl:col-span-3 rounded-2xl border border-dashed border-line p-12 text-center text-sm text-ink-soft"><Camera className="mx-auto h-7 w-7 text-ink-faint"/><p className="mt-3">Upload your normal product images to start.</p></div>}</div>
  </section>}
 </div>
}
