import { NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';
import archiver from 'archiver';
import { PassThrough } from 'stream';
import { getCurrentUser } from '@/lib/supabase/server';
import { supabaseAdmin } from '@/lib/supabase/admin';
import { canUseFeature } from '@/lib/credits';

export const runtime = 'nodejs';

const bodySchema = z.object({
  brandId: z.string().uuid(),
  format: z.enum(['zip', 'react', 'nextjs']).default('zip'),
});

/** Export is free (0 credits) but still plan-gated — Free plan can't export. */
export async function POST(req: NextRequest) {
  const user = await getCurrentUser();
  if (!user) return NextResponse.json({ error: 'Not authenticated.' }, { status: 401 });

  const parsed = bodySchema.safeParse(await req.json());
  if (!parsed.success) return NextResponse.json({ error: 'Invalid request.' }, { status: 400 });
  const { brandId } = parsed.data;

  const gate = await canUseFeature(user, 'export_code');
  if (!gate.allowed) return NextResponse.json({ error: gate.reason, upgradeRequired: true }, { status: 402 });

  const supabase = supabaseAdmin();
  const { data: brand, error } = await supabase
    .from('brands')
    .select('name, description')
    .eq('id', brandId)
    .eq('user_id', user.id)
    .single();
  if (error || !brand) return NextResponse.json({ error: 'Brand not found.' }, { status: 404 });

  // NOTE: this stitches together the site's stored source (already generated by
  // /api/ai/generate-website and persisted per-section) into a project archive.
  // The section source lookup is left as a TODO — plug in wherever generated
  // JSX is stored (a `site_sections` table, or blob storage) once that's built.
  const archive = archiver('zip', { zlib: { level: 9 } });
  const stream = new PassThrough();
  archive.pipe(stream);

  archive.append(
    `# ${brand.name}\n\nGenerated by owbrand (https://owbrand.ai) — built by Techtig.\n\n${brand.description}\n`,
    { name: 'README.md' }
  );
  archive.append(JSON.stringify({ name: brand.name, private: true, dependencies: {} }, null, 2), {
    name: 'package.json',
  });
  archive.finalize();

  return new NextResponse(stream as any, {
    headers: {
      'Content-Type': 'application/zip',
      'Content-Disposition': `attachment; filename="${brand.name.replace(/\s+/g, '-').toLowerCase()}.zip"`,
    },
  });
}
